### PR TITLE
build packages with cmake presets and vcpkg

### LINKED ISSUE #639: jammy aarch64 deb has broken openssl links
`openssl` is installed and links to `libssl.so.3`, but `ziti-edge-tunnel` links to non-existent `libssl.so.1.1`

```
# ubuntu jammy aarch64
$ ldd /opt/openziti/bin/ziti-edge-tunnel
        linux-vdso.so.1 (0x0000ffff909e9000)
        libssl.so.1.1 => not found
        libcrypto.so.1.1 => not found
        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000ffff8e680000)
        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000ffff8e660000)
        libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000ffff8e640000)
        libresolv.so.2 => /lib/aarch64-linux-gnu/libresolv.so.2 (0x0000ffff8e610000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffff8e460000)
        /lib/ld-linux-aarch64.so.1 (0x0000ffff909b0000)

$ apt show ziti-edge-tunnel | grep Depends
Depends: debconf, iproute2, sed, systemd, libatomic1, openssl

$ file /opt/openziti/bin/ziti-edge-tunnel
/opt/openziti/bin/ziti-edge-tunnel: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=6d0815992ea5624d9a52ef79a73827040f29890e, for GNU/Linux 3.7.0, with debug_info, not stripped

$ uname -m
aarch64

$ ldd $(which openssl)
        linux-vdso.so.1 (0x0000ffff8983f000)
        libssl.so.3 => /lib/aarch64-linux-gnu/libssl.so.3 (0x0000ffff89660000)
        libcrypto.so.3 => /lib/aarch64-linux-gnu/libcrypto.so.3 (0x0000ffff89260000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffff890b0000)
        /lib/ld-linux-aarch64.so.1 (0x0000ffff89806000)
```

### PR DESCRIPTION
**Pull request by scareything**
Set up and use vcpkg when building packages

also, fixes #639

### CODE REVIEW

**Comment by qrkourier** [comment]
xenial install errors

```bash
$ apt install -y /tmp/ziti-edge-tunnel*.deb
# truncated
ln: failed to create symbolic link '/usr/lib/systemd/system/ziti-edge-tunnel.service': No such file or directory                                                                       ln: failed to create symbolic link '/usr/lib/systemd/system/ziti-edge-tunnel.service': No such file or directory                                                                       /var/lib/dpkg/info/ziti-edge-tunnel.postinst: 11: /var/lib/dpkg/info/ziti-edge-tunnel.postinst: systemd-sysusers: not found                                                            chown: invalid user: ‘ziti:ziti’                                                                                                                                                       chown: invalid group: ‘root:ziti’                                                                                                                                                      /usr/bin/deb-systemd-helper: error: unable to read ziti-edge-tunnel.service                                                                                                                                                                                                                                                                                                   --------------------------------------------------------------------------------                                                                                                       
ziti-edge-tunnel was installed...                                                                                                                                                      
First install an OpenZiti identity or enroll token in: /opt/openziti/etc/identities                                                                                                    then start or restart this systemd service unit.                                                                                                                                       --------------------------------------------------------------------------------                                                                                                       

$ systemctl cat ziti-edge-tunnel
No files found for ziti-edge-tunnel.service.
```

Missing ziti user and group and systemd service

**Comment by qrkourier** [comment]
Good install, service, and tun device for both RedHat 7,8. Both package installs fail to set up DNS automatically, but I don't think that's new. 

Same errors for Bionic as Xenial and Trusty:

```bash
ln: failed to create symbolic link '/usr/lib/systemd/system/ziti-edge-tunnel.service': No such file or directory
ln: failed to create symbolic link '/usr/lib/systemd/system/ziti-edge-tunnel.service': No such file or directory
systemd-sysusers: unrecognized option '--replace=/usr/lib/sysusers.d/ziti-edge-tunnel.conf'
chown: invalid user: ‘ziti:ziti’
chown: invalid group: ‘root:ziti’
/usr/bin/deb-systemd-helper: error: unable to read ziti-edge-tunnel.service

--------------------------------------------------------------------------------
ziti-edge-tunnel was installed...
First install an OpenZiti identity or enroll token in: /opt/openziti/etc/identities
then start or restart this systemd service unit.
--------------------------------------------------------------------------------
```

**Comment by qrkourier** [comment]
The Focal DEB installs, and I got a few good functional Ziti service results, but sporadic failures as well with logs like these corresponding with each attempt to connect to a Ziti service. I verified the service was authorized with the tunnel_status command. I reproduced this result in a Focal VM and Focal LXC container and could not reproduce it during the same tie frame on my Jammy workstation using an identity from the same ZEDS app.

```bash
$ journalctl -lfu ziti-edge-tunnel
#... truncated
May 03 23:20:26 ubuntu2004.localdomain ziti-edge-tunnel[639]: (639)[      349.625]   ERROR ziti-sdk:channel.c:853 on_channel_connect_internal() ch[1] failed to connect [-103/software caused connection abort]
May 03 23:20:26 ubuntu2004.localdomain ziti-edge-tunnel[639]: (639)[      349.626]   ERROR ziti-sdk:channel.c:853 on_channel_connect_internal() ch[2] failed to connect [-103/software caused connection abort]
May 03 23:20:26 ubuntu2004.localdomain ziti-edge-tunnel[639]: (639)[      349.627]    WARN ziti-sdk:connect.c:1523 process_edge_message() conn[0.7/Closed] data[432 bytes] received in state[Closed]
May 03 23:20:28 ubuntu2004.localdomain ziti-edge-tunnel[639]: (639)[      351.737]   ERROR ziti-sdk:channel.c:483 dispatch_message() ch[0] received message without conn_id or for unknown connection ct[ED72] conn_id[7]
```

**Comment by qrkourier** [comment]
#### Summary of package test

| os      | resolv.conf    | install | tun | dns | summary               |
| ------- | -------------- | ------- | --- | --- | --------------------- |
| redhat7 | NetworkManager | [x]     | [x] | [ ] | manual dns            |
| redhat8 | dhclient       | [x]     | [x] | [ ] | manual dns            |
| trusty  | resolvconf     | [ ]     | [ ] | [ ] | install failed        |
| xenial  | resolvconf     | [ ]     | [ ] | [ ] | install failed        |
| bionic  | resolved       | [ ]     | [ ] | [ ] | install failed        |
| focal   | resolved       | [x]     | [x] | [x] | Ziti service failures | 
| jammy   | resolved       | [x]     | [x] | [x] | OKAY                  |

**Comment by qrkourier** [comment]
trust install error indicates `/usr/lib/systemd/system` dir is needed but doesn't exist.

```
$ yes|dpkg --install /tmp/ziti-edge-tunnel-*.deb || apt-get --yes --fix-broken install
# ... truncated
ln: failed to create symbolic link ‘/usr/lib/systemd/system/ziti-edge-tunnel.service’: No such file or directory
ln: failed to create symbolic link ‘/usr/lib/systemd/system/ziti-edge-tunnel.service’: No such file or directory
/usr/bin/deb-systemd-helper: error: unable to read ziti-edge-tunnel.service

----------------------------------------------------------------------------------------------------------------------------------------------------------------------
ziti-edge-tunnel was installed...
First install an OpenZiti identity or enroll token in: /opt/openziti/etc/identities
then start or restart this systemd service unit.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
Processing triggers for libc-bin (2.19-0ubuntu6.15) ...

root@trusty-test:~# systemctl status ziti-edge-tunnel.service
ziti-edge-tunnel.service
   Loaded: error (Reason: No such file or directory)
   Active: inactive (dead)

root@trusty-test:~# ll /usr/lib/systemd
total 24
drwxr-xr-x  6 root root 4096 May  4 19:06 ./
drwxr-xr-x 57 root root 4096 May  4 19:06 ../
drwxr-xr-x  2 root root 4096 May  4 19:06 catalog/
drwxr-xr-x  2 root root 4096 Nov  7  2019 ntp-units.d/
drwxr-xr-x  2 root root 4096 May  4 19:06 user/
drwxr-xr-x  2 root root 4096 Apr  3  2019 user-generators/

root@trusty-test:~# ll /usr/lib/systemd/system
ls: cannot access /usr/lib/systemd/system: No such file or directory
```

**Comment by sabedevops** [comment]
Seems that on the older distributions, the `/lib` is not a symlink to `/usr/lib`. 

One approach is to set the unit directory for these distro packages builds via `-D SYSTEMD_UNIT_DIR=/lib/systemd/system` after adding an `if (NOT SYSTEMD_UNIT_DIR)` or similar.

**Comment by qrkourier** [comment]
On RedHat8, I encountered the same WARN log that I saw yesterday on Focal coinciding with an empty reply from the Ziti service. This is the first occurence of the anomaly during this batch.

```
May 04 20:17:04 rocky8.localdomain ziti-edge-tunnel[4997]: (4997)[      319.066]    WARN ziti-sdk:connect.c:1523 process_edge_message() conn[0.11/Closed] data[432 bytes] received in state[Closed]
```

[Link to post about this above from yesterday, Wed 3rd at 19:27 EDT](https://github.com/openziti/ziti-tunnel-sdk-c/pull/641#issuecomment-1533877503).

**Comment by qrkourier** [comment]
Ubuntu 18 Bionic install errors

```
ln: failed to create symbolic link '/usr/lib/systemd/system/ziti-edge-tunnel.service': No such file or directory
ln: failed to create symbolic link '/usr/lib/systemd/system/ziti-edge-tunnel.service': No such file or directory
systemd-sysusers: unrecognized option '--replace=/usr/lib/sysusers.d/ziti-edge-tunnel.conf'
chown: invalid user: ‘ziti:ziti’
chown: invalid group: ‘root:ziti’
/usr/bin/deb-systemd-helper: error: unable to read ziti-edge-tunnel.service

--------------------------------------------------------------------------------
ziti-edge-tunnel was installed...
First install an OpenZiti identity or enroll token in: /opt/openziti/etc/identities
then start or restart this systemd service unit.
--------------------------------------------------------------------------------
```

**Comment by qrkourier** [comment]
| os      | resolv.conf    | install | tun | dns | summary              |
| ------- | -------------- | ------- | --- | --- | -------------------- |
| redhat7 | NetworkManager | [x]     | [x] | [ ] | OKAY w/ manual dns   |
| redhat8 | NetworkManager | [x]     | [x] | [ ] | OKAY w/ manual dns   | 
| trusty  | resolvconf     | [ ]     | [ ] | [ ] | install failed       |
| xenial  | resolvconf     | [ ]     | [ ] | [ ] | install failed       |
| bionic  | resolved       | [ ]     | [ ] | [ ] | install failed       |
| focal   | resolved       | [x]     | [x] | [x] | OKAY |
| jammy   | resolved       | [x]     | [x] | [x] | OKAY                 |

**Comment by scareything** [comment]
The install failures on bionic and earlier manifest with this:
```
ERROR ziti-edge-tunnel:resolvers.c:321 set_systemd_resolved_link_setting() Failure calling method: SetLinkLLMNR for link: (tun0): (org.freedesktop.DBus.Error.AccessDenied, Access to org.freedesktop.resolve1.Manager.SetLinkLLMNR() not permitted.)
```

The polkit configuration that the postinstall script drops into /var/lib/polkit-1/localauthority/10-vendor.d/ziti-edge-tunnel.pkla seems to be correct:
```
[Permit ziti-edge-tunnel to configure link DNS]
Identity=unix-user:ziti
Action=org.freedesktop.resolve1.*
ResultAny=yes
```

However that the version of systemd on bionic and earlier does not expose the SetLinkLLMNR method through polkit. Indeed, the associated action isn't registered:

```
vagrant@ubuntu-18:~$ grep "action id" /usr/share/polkit-1/actions/org.freedesktop.resolve1.policy 
        <action id="org.freedesktop.resolve1.register-service">
        <action id="org.freedesktop.resolve1.unregister-service">
```

The method was exposed with [this commit](https://github.com/systemd/systemd/commit/52aaef0f5dc81b9a08d720f551eac53ac88aa596#diff-4a45826ad94fee2e88108e8fa99c24e938add7ff8c0ddf4072c7be896128fb6a), which was released with systemd v243. Bionic has v237:
```
vagrant@ubuntu-18:~$ systemd --version
systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```

So we need to do something else on bionic. @sabedevops mentioned the possibility of dropping privileges only after dns has been configured so that we can munge resolv.conf on the older rh distros. Delaying the drop would also help in this situation, too.

**Comment by qrkourier** [comment]
I confirmed that registering the additional actions with 18.04 Bionic's polkitd did not allow SetLinkLLMNR. I borrowed the actions from 20.04 Focal for this test.

**Review by qrkourier — APPROVED** [review]
advancing package fixes with pre-existing issues related to drop-privs that are being worked in another issue

**Pull request merged**
