### PR TITLE
feat: add static builds presets (1.x)

### LINKED ISSUE #938: [Proposal] Linux static executable releases
Hello there!

I was working on integrating tunneler into Talos Linux and after a discussion on a review it seems like it would be a good idea to provide static binaries for Linux on the Releases page.

PR where discussion happened: https://github.com/siderolabs/extensions/pull/454

~~I could work on this if the proposal's gist is accepted.~~
Linked a PR adding statically linked builds.

### PR DESCRIPTION
**Pull request by scareything**
closes #938 
supersedes #943

### CODE REVIEW

**Comment by qrkourier** [comment]
I'm performing a trial release in my fork before reviewing this pull request: https://github.com/qrkourier/ziti-tunnel-sdk-c/actions

**Comment by qrkourier** [comment]
@scareything Windows build error during the trial release in my fork: https://github.com/qrkourier/ziti-tunnel-sdk-c/actions/runs/10510568961/job/29119517808

```
[1/9] Creating directories for 'wintun-populate'
[1/9] Performing download step (download, verify and extract) for 'wintun-populate'
FAILED: wintun-populate-prefix/src/wintun-populate-stamp/wintun-populate-download D:/a/ziti-tunnel-sdk-c/ziti-tunnel-sdk-c/build/_deps/wintun-subbuild/wintun-populate-prefix/src/wintun-populate-stamp/wintun-populate-download 
cmd.exe /C "cd /D D:\a\ziti-tunnel-sdk-c\ziti-tunnel-sdk-c\build\_deps && D:\a\_temp\507572093\cmake-3.27.7-windows-x86_64\bin\cmake.exe -P D:/a/ziti-tunnel-sdk-c/ziti-tunnel-sdk-c/build/_deps/wintun-subbuild/wintun-populate-prefix/src/wintun-populate-stamp/download-wintun-populate.cmake && D:\a\_temp\507572093\cmake-3.27.7-windows-x86_64\bin\cmake.exe -P D:/a/ziti-tunnel-sdk-c/ziti-tunnel-sdk-c/build/_deps/wintun-subbuild/wintun-populate-prefix/src/wintun-populate-stamp/verify-wintun-populate.cmake && D:\a\_temp\507572093\cmake-3.27.7-windows-x86_64\bin\cmake.exe -P D:/a/ziti-tunnel-sdk-c/ziti-tunnel-sdk-c/build/_deps/wintun-subbuild/wintun-populate-prefix/src/wintun-populate-stamp/extract-wintun-populate.cmake && D:\a\_temp\507572093\cmake-3.27.7-windows-x86_64\bin\cmake.exe -E touch D:/a/ziti-tunnel-sdk-c/ziti-tunnel-sdk-c/build/_deps/wintun-subbuild/wintun-populate-prefix/src/wintun-populate-stamp/wintun-populate-download"
ninja: build stopped: subcommand failed.

CMake Error at D:/a/_temp/507572093/cmake-3.27.7-windows-x86_64/share/cmake-3.27/Modules/FetchContent.cmake:1662 (message):
Error:   Build step for wintun failed: 1
Call Stack (most recent call first):
  D:/a/_temp/507572093/cmake-3.27.7-windows-x86_64/share/cmake-3.27/Modules/FetchContent.cmake:1802:EVAL:2 (__FetchContent_directPopulate)
  D:/a/_temp/50[757](https://github.com/qrkourier/ziti-tunnel-sdk-c/actions/runs/10510568961/job/29119517808#step:4:777)2093/cmake-3.27.7-windows-x86_64/share/cmake-3.27/Modules/FetchContent.cmake:1802 (cmake_language)
  programs/ziti-edge-tunnel/wintun.cmake:10 (FetchContent_Populate)
  programs/ziti-edge-tunnel/CMakeLists.txt:11 (include)


-- Configuring incomplete, errors occurred!

⏱ elapsed: 836.353 seconds
Error: "'D:\a\_temp\507572093\cmake-3.27.7-windows-x86_64\bin\cmake.exe' failed with error code: '1'.
    at CMakeRunner.<anonymous> (D:\a\_actions\lukka\run-cmake\v10.6\dist\index.js:5405:23)
    at Generator.next (<anonymous>)
    at fulfilled (D:\a\_actions\lukka\run-cmake\v10.6\dist\index.js:5220:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: run-cmake action execution failed: 'Error: "'D:\a\_temp\507572093\cmake-3.27.7-windows-x86_64\bin\cmake.exe' failed with error code: '1'.'
```

**Review by qrkourier — APPROVED** [review]
mock release in my fork succeeded: https://github.com/qrkourier/ziti-tunnel-sdk-c/actions/runs/10511152376

**Comment by nenkoru** [comment]
That is awesome, guys!
Can't wait for a new release!

**Comment by scareything** [comment]
Thanks for contributing, @nenkoru! The first release that includes static binaries is [1.1.3](https://github.com/openziti/ziti-tunnel-sdk-c/releases/tag/v1.1.3).

**Pull request merged**
